(package "company-coffee"
         "0.0.1"
         "Emacs coffee completion")

(website-url "https://github.com/elp-revive/company-coffee")
(keywords "convenience")

(package-file "company-coffee.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "company")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
